### ISSUE TITLE
More intelligent GPU usage display

### ISSUE THREAD

**Issue by chrissamuel** [chanconrad/OzSTAR-Job-Monitor#1]
Currently bobMon2 displays both GPUs for jobs, even if they've requested just one (or neither).

It would be nice if jobs that didn't request GPUs didn't have anything displayed there and jobs that requested one GPU only have the GPU usage for the one they've been allocated displayed.

You can see which GPU has been allocated to which job on which node via (for example):

```
[root@transom1` ~]# scontrol show job -d 81454 | fgrep GRES_IDX
     Nodes=john4 CPU_IDs=0 Mem=5120 GRES_IDX=gpu(IDX:0)

```

Thanks!

**Comment by chanconrad** [comment]
Hi chris,

Do you mean on the mini charts in the middle panel, or on the node chart on the right panel? At the moment, the right panel shows node-wide statistics. On my todo list is to see if pyslurm shows which GPU has been allocated to the job, otherwise we'll have to write something that runs the scontrol command. for every job.

**Comment by chrissamuel** [comment]
Ahh thanks Conrad, I keep forgetting you're relying on pyslurm.
I was thinking you were doing "scontrol show job" and parsing that output.

**Comment by chrissamuel** [comment]
It looks like PySlurm can get info about GRES allocations looking at this issue complaining about how the change in the previous major version (17.02.x) broke it.   Not yet fixed though... https://github.com/PySlurm/pyslurm/issues/104

**Comment by chanconrad** [comment]
Thanks! I'll keep an eye on this and implement it when they fix it.

**Comment by chrissamuel** [comment]
OK, that issue is about the GresUsed attribute for nodes, not GRES_IDX.  I'll open a new issue for that.

**Comment by chrissamuel** [comment]
Question from the PySlurm folks: 

> How would you like the output of this attribute, as one string that matches the scontrol output, or a list of strings if there are more than one?

**Comment by chanconrad** [comment]
Sorry for the late reply... a list of strings would be great!

**Comment by chrissamuel** [comment]
Thanks Conrad, just passed that back to them now.

**Comment by chrissamuel** [comment]
FYI, from the pyslurm folks:

> The gres_idx branch should work with a later version of Cython. I'll merge it into master soon after I figure out why it is failing on older Cython versions.

**Comment by chrissamuel** [comment]
PySlurm has now got the requested ability - info here: https://github.com/PySlurm/pyslurm/issues/116#issuecomment-2569600935
